#!/usr/bin/env bun
/**
 * Generates src/build-info.ts with version, git commit, and build timestamp.
 * Run before each build.
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync('package.json', 'utf-8'));
const version: string = pkg.version;

let gitCommit = 'unknown';
let gitDirty = false;
try {
  gitCommit = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
  const status = execSync('git status --porcelain', { encoding: 'utf-8' }).trim();
  gitDirty = status.length > 0;
} catch {
  // Not a git repo or git not available
}

const buildTimestamp = new Date().toISOString();

const content = `// Auto-generated by scripts/gen-build-info.ts — do not edit
export const BUILD_INFO = {
  version: '${version}',
  gitCommit: '${gitCommit}${gitDirty ? '-dirty' : ''}',
  buildTimestamp: '${buildTimestamp}',
} as const;
`;

writeFileSync('src/build-info.ts', content);
console.error(`[gen-build-info] v${version} ${gitCommit}${gitDirty ? '-dirty' : ''} @ ${buildTimestamp}`);
